# Generated by Django 3.2.7 on 2023-12-29 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Drive', '0019_auto_20231229_2245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(blank=True, upload_to='Account')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkek'), ('F', 'Kadin')], max_length=1, null=True, verbose_name='Cinsiyet')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.contact')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.department')),
                ('scholl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.scholl')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
