# Generated by Django 3.2.7 on 2023-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Erkek'), ('F', 'Kadın')], max_length=1, null=True, verbose_name='Cinsiyet'),
        ),
    ]
