# Generated by Django 3.2.7 on 2023-12-09 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=400)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scholl',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('image_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Erkek'), ('F', 'Kadin')], max_length=1, null=True)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.contact')),
                ('department', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.department')),
                ('scholl', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.scholl')),
            ],
        ),
        migrations.CreateModel(
            name='Outhor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('biography', models.CharField(blank=True, max_length=3000, null=True)),
                ('image_name', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Erkek'), ('F', 'Kadin')], max_length=1)),
                ('title_type', models.CharField(choices=[('1', 'Profesör'), ('2', 'Doçent'), ('3', 'Doktor'), ('4', 'Öğretim Görevlisi'), ('5', 'Araştirma Görevlisi'), ('6', 'Öğretmen'), ('7', 'Yazar'), ('8', 'Araştirmaci'), ('9', 'Üye')], max_length=1)),
                ('contact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.contact')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ManyToManyField(to='Drive.Department')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(15)])),
                ('file_name', models.CharField(max_length=200)),
                ('file_cover', models.CharField(blank=True, max_length=200, null=True)),
                ('upload_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('language', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.department')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.lesson')),
                ('outhor', models.ManyToManyField(to='Drive.Outhor')),
                ('scholl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.scholl')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Drive.owner')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='scholl',
            field=models.ManyToManyField(to='Drive.Scholl'),
        ),
    ]
