# Generated by Django 3.2.7 on 2023-12-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outhor',
            name='biography',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
