# Generated by Django 3.2.7 on 2023-12-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0005_auto_20231214_1946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='outhor',
        ),
        migrations.AddField(
            model_name='file',
            name='outhor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Drive.outhor'),
        ),
    ]
