# Generated by Django 3.2.7 on 2023-12-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0006_auto_20231214_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='outhor',
        ),
        migrations.AddField(
            model_name='file',
            name='outhor',
            field=models.ManyToManyField(to='Drive.Outhor'),
        ),
    ]
