# Generated by Django 3.2.7 on 2023-12-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0010_auto_20231216_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='outhor',
        ),
        migrations.AddField(
            model_name='file',
            name='outhor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Drive.outhor'),
            preserve_default=False,
        ),
    ]
