# Generated by Django 3.2.7 on 2023-12-16 15:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0012_auto_20231216_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
