# Generated by Django 3.2.7 on 2023-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0014_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Posta'),
        ),
    ]
