# Generated by Django 3.2.7 on 2023-12-17 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0016_auto_20231217_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Drive.file'),
        ),
    ]
