# Generated by Django 3.2.7 on 2023-12-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0018_comment_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Yorum', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yorum Tarihi'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='E-Posta'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.IntegerField(null=True, verbose_name='Oy'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Yorum'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=30, verbose_name='Kullanıcı Adı'),
        ),
    ]
