# Generated by Django 3.2.7 on 2023-12-29 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0019_auto_20231229_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Kullanıcı',
        ),
    ]
