# Generated by Django 3.2.7 on 2023-12-29 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0021_alter_file_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kullanıcı',
        ),
    ]
