# Generated by Django 3.2.7 on 2023-12-29 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0023_auto_20231230_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
