# Generated by Django 3.2.7 on 2023-12-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0024_slider_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_name',
            field=models.FileField(upload_to='Drive', verbose_name='Dosya Adı'),
        ),
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(choices=[('1', 'Türkçe'), ('2', 'İngilizce'), ('3', 'Fransızca'), ('4', 'Almanca'), ('5', 'İtalyanca')], max_length=100, verbose_name='Dil'),
        ),
    ]
