# Generated by Django 3.2.7 on 2023-12-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0026_auto_20231231_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Drive', verbose_name='Bölüm Logosu'),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='scholl',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='Drive', verbose_name='Bölüm Logosu'),
        ),
        migrations.AddField(
            model_name='scholl',
            name='description',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Açıklama'),
        ),
    ]
