# Generated by Django 3.2.7 on 2023-12-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0027_auto_20231231_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='language',
            field=models.CharField(choices=[('Türkçe', 'Türkçe'), ('İngilizce', 'İngilizce'), ('Fransızca', 'Fransızca'), ('Almanca', 'Almanca'), ('İtalyanca', 'İtalyanca')], max_length=100, verbose_name='Dil'),
        ),
    ]
