# Generated by Django 3.2.7 on 2024-01-04 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Drive', '0028_alter_file_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outhor',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to='Drive', verbose_name='Profil Resmi'),
        ),
    ]
