# Generated by Django 3.2.7 on 2024-01-01 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OCRApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='ocrdocument',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='ocr_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ocrdocument',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
