# Generated by Django 3.2.7 on 2024-01-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OCRApp', '0002_auto_20240101_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
